"""Run each generated manufacturing source through process_event exactly once."""

from __future__ import annotations

import argparse
import asyncio
import os
import sys
from collections import Counter

from sqlalchemy import select, text
from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.config import settings
from app.models import CrossRegionReport, PurchaseOrder, WarrantyClaim
from app.schemas import RiskCheckRequest
from app.service.event import process_event


async def _reset_generated_risk_data(session) -> None:
    """Delete only Step 6 ML-prefixed derived risk records, in dependency order."""
    await session.execute(text("""
        DELETE FROM risk_action_log
        WHERE target_type='case' AND target_id IN (
            SELECT case_id FROM risk_case WHERE source_id LIKE 'ML%'
        )
    """))
    await session.execute(text("DELETE FROM risk_case WHERE source_id LIKE 'ML%'"))
    await session.execute(text("""
        DELETE FROM risk_assessment WHERE event_id IN (
            SELECT event_id FROM risk_event WHERE event_source_id LIKE 'ML%'
        )
    """))
    await session.execute(text("""
        DELETE FROM risk_feature WHERE event_id IN (
            SELECT event_id FROM risk_event WHERE event_source_id LIKE 'ML%'
        )
    """))
    await session.execute(text("DELETE FROM risk_event WHERE event_source_id LIKE 'ML%'"))
    await session.execute(text("DELETE FROM risk_user_profile WHERE user_id LIKE 'MLD%'"))
    await session.commit()


async def _collect_sources(session) -> list[tuple[str, str, str]]:
    blacklisted = set((await session.execute(text("""
        SELECT blacklist_value FROM risk_blacklist
        WHERE blacklist_type='用户' AND deleted_at IS NULL
          AND (expire_time IS NULL OR expire_time > NOW())
    """))).scalars().all())

    sources: list[tuple[str, str, str]] = []
    orders = (await session.execute(
        select(PurchaseOrder.po_id, PurchaseOrder.dealer_id)
        .where(PurchaseOrder.po_id.like("MLPO%"))
        .order_by(PurchaseOrder.po_id)
    )).all()
    for po_id, dealer_id in orders:
        if dealer_id in blacklisted:
            continue
        # Large new-dealer sources must use 下单 so R003 supplies their weak label.
        event_type = "下单"
        if not (await session.execute(text(
            "SELECT authorized_at >= DATE_SUB(CURDATE(), INTERVAL 30 DAY) "
            "AND total_amount >= 1000000 FROM dealer JOIN purchase_order USING(dealer_id) "
            "WHERE po_id=:po_id"
        ), {"po_id": po_id})).scalar():
            event_type = "支付" if int(po_id[-2:]) % 2 == 0 else "下单"
        sources.append((event_type, po_id, dealer_id))

    claims = (await session.execute(
        select(WarrantyClaim.claim_id, WarrantyClaim.dealer_id)
        .where(WarrantyClaim.claim_id.like("MLCLM%"))
        .order_by(WarrantyClaim.claim_id)
    )).all()
    sources.extend(
        ("售后申请", claim_id, dealer_id)
        for claim_id, dealer_id in claims if dealer_id not in blacklisted
    )

    reports = (await session.execute(text("""
        SELECT r.report_id, d.dealer_id
        FROM cross_region_report AS r
        JOIN device AS d ON d.device_id = r.device_id
        WHERE r.report_id LIKE 'MLCRR%'
        ORDER BY r.report_id
    """))).all()
    sources.extend(
        ("物流投诉", report_id, dealer_id)
        for report_id, dealer_id in reports if dealer_id not in blacklisted
    )
    return sources


async def generate_risk_data(
    *, db_name: str, reset: bool = False, limit: int | None = None
) -> dict[str, int]:
    engine = create_async_engine(settings.get_database_url_async(db_name), pool_pre_ping=False)
    session_factory = async_sessionmaker(engine, expire_on_commit=False)
    decisions: Counter[str] = Counter()
    event_types: Counter[str] = Counter()
    try:
        async with session_factory() as session:
            if reset:
                await _reset_generated_risk_data(session)
            sources = await _collect_sources(session)
            if limit is not None:
                sources = sources[:limit]

            # Weak labels in this batch must be generated by JSON rules only.
            # This runtime-only switch does not modify decision.py or ml_model.py.
            from app.engine import ml_model
            ml_model._MODEL = None
            ml_model._LOADED = False

            for index, (event_type, source_id, dealer_id) in enumerate(sources, 1):
                response = await process_event(session, RiskCheckRequest(
                    event_type=event_type,
                    source_id=source_id,
                    user_id=dealer_id,
                    event_data={"step6_dataset": True},
                ))
                decisions[response.decision] += 1
                event_types[event_type] += 1
                if index % 100 == 0 or index == len(sources):
                    print(f"process_event {index}/{len(sources)}")

            # Only the just-generated ML-prefixed weak-label batch is marked for
            # snapshot backfill. No unrelated historical assessment is touched.
            await session.execute(text("""
                UPDATE risk_assessment AS a
                JOIN risk_event AS e ON e.event_id = a.event_id
                SET a.ml_score = NULL, a.ml_decision = NULL
                WHERE e.event_source_id LIKE 'ML%'
            """))
            await session.commit()
    finally:
        await engine.dispose()

    result = {
        "events": sum(event_types.values()),
        "label_0": decisions["通过"] + decisions["标记"],
        "label_1": decisions["人工审核"] + decisions["拒绝"],
        **{f"event_{key}": value for key, value in event_types.items()},
    }
    print("制造业风险事件完成:", result)
    print("决策分布:", dict(decisions))
    return result


def main() -> None:
    parser = argparse.ArgumentParser(description="制造业业务源 → process_event → 25维快照")
    parser.add_argument("--db", default=settings.DB_NAME)
    parser.add_argument("--limit", type=int)
    parser.add_argument("--reset", "--clean", action="store_true",
                        help="仅清理 ML* 来源的风控派生记录")
    args = parser.parse_args()
    asyncio.run(generate_risk_data(db_name=args.db, reset=args.reset, limit=args.limit))


if __name__ == "__main__":
    main()
