-- ============================================
-- 物流风控系统 - 数据库初始化指南
-- ============================================
--
-- 本系统共需初始化 4 个 SQL 脚本，按以下顺序执行:
--
--   1. init_business_tables.sql  -- 5 张物流业务表 (DDL)
--   2. init_business_data.sql    -- 业务表测试数据 (120+ 运单)
--   3. init_risk_tables.sql      -- 9 张风控表 (DDL)
--   4. init_risk_data.sql        -- 9 条预置物流风控规则 (R001-R025)
--
-- ============================================
-- 使用方式
-- ============================================
--
-- 方式1 (推荐): 一键 Python 脚本
--   conda activate risk
--   python scripts/init_db.py
--
-- 方式2: 手动按顺序执行 (在项目根目录下)
--   mysql -u root -p123321 --default-character-set=utf8mb4 ecs < sql/init_business_tables.sql
--   mysql -u root -p123321 --default-character-set=utf8mb4 ecs < sql/init_business_data.sql
--   mysql -u root -p123321 --default-character-set=utf8mb4 ecs < sql/init_risk_tables.sql
--   mysql -u root -p123321 --default-character-set=utf8mb4 ecs < sql/init_risk_data.sql
--
-- 方式3: 仅创建数据库结构 (不含数据)
--   mysql -u root -p123321 --default-character-set=utf8mb4 ecs < sql/init_business_tables.sql
--   mysql -u root -p123321 --default-character-set=utf8mb4 ecs < sql/init_risk_tables.sql
--
-- 老环境升级 (2026-08-07 之后首次启动):
-- 新装环境无需 migration; 老环境升级参考基线 README.
--
-- 注: 原 migration_add_case_source_id.sql 已合并到 migration_add_2026_08_07_fields.sql (项 5/6/7)
--     仅保留作为历史兼容, 不再被 init_db.py 调用
--
-- ============================================
-- 注意事项
-- ============================================
-- - 数据库名: tour_risk (需提前创建)
-- - 字符集: utf8mb4
-- - 风控表 9 张: risk_rule / risk_event / risk_feature / risk_assessment /
--               risk_case / risk_blacklist / risk_user_profile /
--               risk_action_log / risk_alert
-- - 业务表 5 张: user_info / address / shipment / shipment_item / blacklist_extra
