-- ============================================
-- 制造业风控系统 - 数据库初始化指南
-- ============================================
--
-- 本系统共需初始化 4 个 SQL 脚本，按以下顺序执行:
--
--   1. init_business_tables.sql  -- 7 张业务表 (DDL)
--   2. init_business_data.sql    -- 业务表测试数据 (300+ 订单)
--   3. init_risk_tables.sql      -- 9 张风控表 (DDL, 含 P4 2 张)
--   4. init_risk_data.sql        -- 16 条预置风控规则 (R001-R030)
--
-- ============================================
-- 使用方式
-- ============================================
--
-- 方式1 (推荐): 一键 Python 脚本
--   conda activate risk
--   python scripts/init_db.py
--
-- 方式2: 手动按顺序执行 (在项目根目录下)
--   mysql -u root -p123456 --default-character-set=utf8mb4 mfg_risk < sql/init_business_tables.sql
--   mysql -u root -p123456 --default-character-set=utf8mb4 mfg_risk < sql/init_business_data.sql
--   mysql -u root -p123456 --default-character-set=utf8mb4 mfg_risk < sql/init_risk_tables.sql
--   mysql -u root -p123456 --default-character-set=utf8mb4 mfg_risk < sql/init_risk_data.sql
--
-- 方式3: 仅创建数据库结构 (不含数据)
--   mysql -u root -p123321 --default-character-set=utf8mb4 ecs < sql/init_business_tables.sql
--   mysql -u root -p123321 --default-character-set=utf8mb4 ecs < sql/init_risk_tables.sql
--
-- ============================================
-- 注意事项
-- ============================================
-- - 数据库名: mfg_risk (需提前创建)
-- - 字符集: utf8mb4
-- - 业务表按外键依赖排序，可安全顺序执行
-- - 业务数据脚本已包含 SET FOREIGN_KEY_CHECKS = 0 处理
-- - 如需清空重建，init_business_tables.sql 中所有表使用 DROP TABLE IF EXISTS
-- - 风控表 9 张 (含系统管理表 risk_action_log / risk_alert)
-- - 制造业版为全新库, 不需要跑历史 migration (已从仓库移除)
